version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db_cont
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - mysql-data-django:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - django-notes-app

  django:
    build:
      context: .
    container_name: django_cont
    command: sh -c "python manage.py migrate --no-input && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - django-notes-app
    depends_on: 
      - db
    env_file:
      - ".env"
    restart: always

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    networks:
      - django-notes-app
    depends_on:
      - django

volumes:
  mysql-data-django:

networks:
  django-notes-app:
